name: Remote Dispatch Action Initiator
on:
  repository_dispatch:
jobs:
  build-mwu-with-jina:
    runs-on: ubuntu-latest
    steps:
      - name: POD-UPLOAD - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/jina-ai/cloud-ops/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pod-upload", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
